clusterResourceNamespace: cert-manager
ingressShim:
  defaultIssuerGroup: cert-manager.io
  defaultIssuerKind: ClusterIssuer
  defaultIssuerName: letsencrypt-production
installCRDs: true
prometheus:
  enabled: true
  servicemonitor:
    enabled: true
securityContext:
  fsGroup: 1001
serviceAccount:
  create: false
  name: cert-manager
