alertmanager:
  enabled: true
grafana:
  additionalDataSources:
  - access: proxy
    basicAuth: false
    editable: true
    name: Loki
    type: loki
    url: http://loki.loki.svc.cluster.local:3100
  adminPassword: abc123 # update
  enabled: true
  persistence:
    enabled: true
    size: "8Gi"
  grafana.ini:
    analytics:
      check_for_updates: true
    grafana_net:
      url: https://grafana.net
    log:
      mode: console
    paths:
      data: /var/lib/grafana/
      logs: /var/log/grafana
      plugins: /var/lib/grafana/plugins
      provisioning: /etc/grafana/provisioning
    server:
      domain: grafana.pvcy.customer.com # update
      root_url: https://grafana.pvcy.customer.com/ # update
prometheus:
  enabled: true
  prometheusSpec:
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 50Gi
    ruleSelectorNilUsesHelmValues: false
    ruleSelector: {}
prometheusOperator:
  enabled: true
