loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
monitoring:
  lokiCanary:
    enabled: false
singleBinary:
  replicas: 1
test:
  enabled: false
