apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: email@customer.com
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - selector:
          dnsZones:
            - 'pvcy.customer.com'
        dns01:
          azureDNS:
            hostedZoneName: 'pvcy.customer.com'
            resourceGroupName: 'privacy-dynamics-group'
            subscriptionID: '111222333555'
            managedIdentity:
              clientID: '111222333'
