clusterResourceNamespace: cert-manager
ingressShim:
  defaultIssuerGroup: cert-manager.io
  defaultIssuerKind: ClusterIssuer
  defaultIssuerName: letsencrypt-production # update
installCRDs: true
podLabels:
  azure.workload.identity/use: "true"
prometheus:
  enabled: true
  servicemonitor:
    enabled: true # for Prometheus metric collection
serviceAccount:
  labels:
    azure.workload.identity/use: "true"
